### ISSUE TITLE
API shape: how about navigator.contacts.XXX ?

### ISSUE THREAD

**Issue by inexorabletash** [beverloo/contact-api#1]
`navigator.selectContacts()` makes me wonder about potential future operations, such as "add contact". (Okay, that's the only one I can think of right now beyond generic edit/delete things that make far less sense.) 

Rather than dumping such operations on `navigator` directly, WDYT about `navigator.contacts.select()`?

**Comment by beverloo** [comment]
I like it, thanks! A method to add contacts makes sense to me, and it could potentially reuse `ContactInfo` too in a dictionary form. I don't want to definitively shut the door on some sort of _contact management_ API, but also don't feel we'd want that anytime in the near future.
