### ISSUE TITLE
Input validation

### ISSUE THREAD

**Issue by finnurbreki** [beverloo/contact-api#10]
What is the expected outcome of calling:

select({});
select({multiple: true});
select({properties: ['name']});
select({multiple: true, properties: []});
select({multiple: true, properties: ['foo']});

**Comment by beverloo** [comment]
Thanks! I added a clarification.

> select({});

`TypeError` as at least one property must be provided.

> select({multiple: true});

`TypeError` as at least one property must be provided.

> select({properties: ['name']});

A picker will be shown. (`multiple` has a default value.)

> select({multiple: true, properties: []});

`TypeError` as at least one property must be provided.

> select({multiple: true, properties: ['foo']});

A picker will be shown.
