### ISSUE TITLE
interface ContactInfo: Should name be a sequence?

### ISSUE THREAD

**Issue by inexorabletash** [beverloo/contact-api#3]
_Contacts_ are not the same as _people_. [People don't necessarily have a single name](https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/). We could decide that a contact has at most one name for the purposes of this API, but maybe that's too opinionated.

I'm somewhat torn on this one, since I think developers will get it wrong. We definitely _don't_ want to expose e.g. first, last (as that is definitely wrong, see link above); the alternative is that we have the OS/User Agent canonically produce a single representative name from the data we have about a contact. I suspect that's the best experience all around, but should be documented as an explicit requirement.

**Comment by beverloo** [comment]
Agreed, thank you. It'd be good to not lock ourselves in place anywhere in the API.
