### ISSUE TITLE
ContactInfo can be a dictionary

### ISSUE THREAD

**Issue by annevk** [beverloo/contact-api#8]
I don't see a need for a class here with properties that return frozen arrays. Let's just make it a plain object with normal arrays (sequence in IDL).

**Comment by annevk** [comment]
USVString seems nice to guarantee by the way. Seems unlikely we'd need to allow lone surrogates here.

**Comment by beverloo** [comment]
Agreed, thanks for the feedback. Domenic commented on the interface -> dictionary too in #5.
